#!/usr/bin/env python3
"""Write the pre-model GIS source registry and frozen feature specification."""

from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT / "outputs/tables"
REPORTS = ROOT / "outputs/reports"


ROWS = [
    {
        "priority": 1,
        "feature_family": "historical flood exposure",
        "dataset": "Global Flood Database v1",
        "publisher": "Cloud to Street / Dartmouth Flood Observatory; Earth Engine catalog",
        "source_url": "https://developers.google.com/earth-engine/datasets/catalog/GLOBAL_FLOOD_DB_MODIS_EVENTS_V1",
        "spatial_resolution": "250 m event classification; catalog delivery retains 30 m grid",
        "temporal_coverage": "2000-2018",
        "license_access": "CC BY-NC 4.0; Earth Engine research access",
        "proposed_variable": "gfd_ever_flooded_land_share_2000_2018",
        "district_transform": "Union event flooded pixels; exclude JRC permanent water; flooded land area / valid district land area",
        "time_rule": "Universally pre-period; fixed across events",
        "model_role": "PRIMARY hazard construct",
        "download_status": "metadata verified; not downloaded",
        "main_limitation": "Selected reported/mapped events, not a complete flood climatology; noncommercial license",
    },
    {
        "priority": 2,
        "feature_family": "settlement intensity",
        "dataset": "GHS-BUILT-S R2023A, epoch 2020",
        "publisher": "European Commission Joint Research Centre / Copernicus GHSL",
        "source_url": "https://human-settlement.emergency.copernicus.eu/dataToolsOverview.php",
        "spatial_resolution": "100 m preferred",
        "temporal_coverage": "1975-2020 observed/modelled epochs at 5-year intervals; later projections available",
        "license_access": "Open and free GHSL data",
        "proposed_variable": "ghsl_built_surface_share_2020",
        "district_transform": "Sum built-up square metres / district land square metres",
        "time_rule": "2020 epoch is universally pre-period",
        "model_role": "PRIMARY settlement/opportunity construct",
        "download_status": "metadata verified; not downloaded",
        "main_limitation": "Built-up surface is a proxy for opportunity, not employment or wages",
    },
    {
        "priority": 3,
        "feature_family": "urban accessibility",
        "dataset": "Travel time to cities and ports in 2015",
        "publisher": "Malaria Atlas Project / University of Oxford; Figshare distribution",
        "source_url": "https://figshare.com/articles/dataset/Travel_time_to_cities_and_ports_in_the_year_2015/7638134",
        "spatial_resolution": "30 arc seconds (~1 km)",
        "temporal_coverage": "2015",
        "license_access": "Public Figshare dataset; verify file-specific license on download",
        "proposed_variable": "travel_time_city_ge_50k_median_2015",
        "district_transform": "Median land-pixel minutes to nearest settlement >=50,000; population-weighted mean as sensitivity",
        "time_rule": "Universally pre-period; fixed across events",
        "model_role": "PRIMARY accessibility construct",
        "download_status": "metadata verified; not downloaded",
        "main_limitation": "Modelled relative accessibility, not observed trip time; 2015 network",
    },
    {
        "priority": 4,
        "feature_family": "agricultural land dependence",
        "dataset": "ESA WorldCover 2020 v100",
        "publisher": "European Space Agency WorldCover consortium",
        "source_url": "https://esa-worldcover.org/en/data-access",
        "spatial_resolution": "10 m",
        "temporal_coverage": "2020 map; 2021 map separately available",
        "license_access": "CC BY 4.0; COG/AWS/Zenodo delivery",
        "proposed_variable": "worldcover_cropland_share_2020",
        "district_transform": "Cropland-class land area / valid district land area",
        "time_rule": "2020 version is universally pre-period",
        "model_role": "PRIMARY agriculture construct",
        "download_status": "metadata verified; not downloaded",
        "main_limitation": "Global overall accuracy 74.4%; 2020 and 2021 versions use different algorithms and must not be differenced",
    },
    {
        "priority": 5,
        "feature_family": "surface-water and river-change exposure",
        "dataset": "JRC Global Surface Water",
        "publisher": "European Commission Joint Research Centre / Google",
        "source_url": "https://global-surface-water.appspot.com/download",
        "spatial_resolution": "30 m",
        "temporal_coverage": "1984-2024; yearly/monthly history and summary layers",
        "license_access": "Copernicus; free without restriction of use with acknowledgement",
        "proposed_variable": "jrc_seasonal_or_permanent_water_share_through_2020",
        "district_transform": "Water-observed area share through 2020; separately compute water gain/loss within a river-corridor mask",
        "time_rule": "Truncate at 2020 universally; event-specific later histories only after timing gate",
        "model_role": "HAZARD robustness and erosion proxy",
        "download_status": "metadata verified; not downloaded",
        "main_limitation": "Water occurrence/change is not direct riverbank erosion; 2022-2024 layers would be post-choice for some events",
    },
    {
        "priority": 6,
        "feature_family": "economic activity",
        "dataset": "VIIRS annual nighttime lights VNL v2",
        "publisher": "Earth Observation Group, Colorado School of Mines",
        "source_url": "https://eogdata.mines.edu/products/vnl/",
        "spatial_resolution": "15 arc seconds (~500 m)",
        "temporal_coverage": "Annual consistently processed series from 2012; 2020 documented baseline",
        "license_access": "Download service; verify product terms at acquisition",
        "proposed_variable": "viirs_log_radiance_sum_2020",
        "district_transform": "log1p(sum background-screened radiance over district); lit-area share sensitivity",
        "time_rule": "Use 2020 universally; do not use event-year composites in first model",
        "model_role": "Settlement/opportunity robustness, not additional primary coefficient",
        "download_status": "metadata verified; not downloaded",
        "main_limitation": "Proxy affected by electrification, blooming, and non-employment light sources",
    },
    {
        "priority": 7,
        "feature_family": "population distribution",
        "dataset": "GHS-POP R2023A, epoch 2020",
        "publisher": "European Commission Joint Research Centre / Copernicus GHSL",
        "source_url": "https://human-settlement.emergency.copernicus.eu/dataToolsOverview.php",
        "spatial_resolution": "100 m or 1 km product",
        "temporal_coverage": "1975-2020 epochs plus projections",
        "license_access": "Open and free GHSL data",
        "proposed_variable": "ghsl_population_2020",
        "district_transform": "Sum grid population within district; mass-preserving boundary allocation",
        "time_rule": "Use 2020 as leakage-safe gravity sensitivity",
        "model_role": "Replace—not add to—BBS 2022 gravity population in strict timing sensitivity",
        "download_status": "metadata verified; not downloaded",
        "main_limitation": "Modelled gridded population; correlated with built-up area and must not enter redundantly",
    },
    {
        "priority": 8,
        "feature_family": "rainfall climate and extremes",
        "dataset": "CHIRPS v3 final",
        "publisher": "Climate Hazards Center, UC Santa Barbara",
        "source_url": "https://www.chc.ucsb.edu/data/chirps3",
        "spatial_resolution": "0.05 degrees",
        "temporal_coverage": "1981 to near-present",
        "license_access": "GeoTIFF/NetCDF/BIL/COG; confirm version-specific citation",
        "proposed_variable": "chirps_extreme_rain_days_climatology_through_2020",
        "district_transform": "District mean annual count above local 95th percentile, 1981-2020",
        "time_rule": "Use climatology ending 2020 universally; event-window measures only in a separate origin-shock validation",
        "model_role": "SECONDARY hazard robustness",
        "download_status": "metadata verified; not downloaded",
        "main_limitation": "Rainfall is not flooding; 0.05-degree cells are coarse for small districts",
    },
    {
        "priority": 9,
        "feature_family": "observed event flood extent",
        "dataset": "Copernicus Global Flood Monitoring",
        "publisher": "Copernicus Emergency Management Service / European Commission JRC",
        "source_url": "https://european-flood.emergency.copernicus.eu/sites/default/files/AM/AM2024/data%20availability%20and%20download.pdf",
        "spatial_resolution": "20 m pixel sampling",
        "temporal_coverage": "Full archive from 2015 to ongoing",
        "license_access": "STAC/API/UI access; verify operational product terms before bulk acquisition",
        "proposed_variable": "gfm_prior_flooded_share_before_event_cutoff",
        "district_transform": "Union quality-screened ensemble flood extent strictly before each event cutoff / district land area",
        "time_rule": "Event-specific only; never include flood observations after strict cutoff",
        "model_role": "LATER dynamic robustness, excluded from first static model",
        "download_status": "metadata verified; not downloaded",
        "main_limitation": "Complex event-time processing and cloud/radar/exclusion-mask issues; high leakage risk if cutoff is mishandled",
    },
    {
        "priority": 10,
        "feature_family": "roads, markets, schools, health facilities",
        "dataset": "No nationally complete historical snapshot yet verified",
        "publisher": "TBD",
        "source_url": "",
        "spatial_resolution": "TBD",
        "temporal_coverage": "TBD",
        "license_access": "TBD",
        "proposed_variable": "deferred",
        "district_transform": "Do not construct from current OSM/facility points without a dated pre-period snapshot",
        "time_rule": "Must predate 2021 for universal static use",
        "model_role": "HOLD",
        "download_status": "blocked on temporal provenance, not data availability",
        "main_limitation": "Current snapshots risk encoding post-move infrastructure and differential mapping effort",
    },
]


def main():
    registry = pd.DataFrame(ROWS).sort_values("priority")
    registry["metadata_verified_date"] = "2026-08-28"
    registry.to_csv(TABLES / "bemp_stage3_gis_source_registry.csv", index=False)

    lines = [
        "# BEMP Stage 3 frozen GIS feature specification",
        "",
        "## Scope",
        "",
        "This is a pre-model specification. No raster has been joined to BEMP and no final GIS model has "
        "been estimated. The purpose is to freeze source choices, time rules, transforms, and rejection "
        "criteria before observing model improvements.",
        "",
        "## First static GIS comparison: exactly four constructs",
        "",
        "| Construct | Frozen source/year | Frozen district variable | Directional hypothesis |",
        "|---|---|---|---|",
        "| Historical flood exposure | Global Flood Database, 2000–2018 | `gfd_ever_flooded_land_share_2000_2018` | Ambiguous: avoidance versus floodplain livelihood/urban concentration |",
        "| Settlement intensity | GHSL built-up surface, 2020 | `ghsl_built_surface_share_2020` | Positive |",
        "| Urban accessibility | Travel time to cities, 2015 | `travel_time_city_ge_50k_median_2015` | Negative coefficient on travel minutes |",
        "| Agricultural land | ESA WorldCover, 2020 | `worldcover_cropland_share_2020` | Context-dependent; likely positive for agrarian movers, negative for urban moves |",
        "",
        "Distance and population remain benchmark controls. For a strict timing sensitivity, replace BBS "
        "2022 population with GHS-POP 2020; do not include both. Standardize continuous variables across "
        "the 64 candidate districts using training-fold means and standard deviations only.",
        "",
        "## Time rules",
        "",
        "- 2020 is the only universal static reference year supported by every event cutoff.",
        "- A 2021 or later annual layer may be used only when the event ledger's `latest_complete_annual_feature_year` permits it.",
        "- Dynamic rasters must be truncated at `strict_feature_cutoff_date` separately for every event.",
        "- The 2022 BBS population remains a transparent benchmark exposure, not a universally pre-choice causal predictor.",
        "- Current OSM roads or facility registries are prohibited until a dated historical snapshot is verified.",
        "",
        "## Raster processing contract",
        "",
        "1. Preserve each source raster and checksum it before processing.",
        "2. Reproject Bangladesh districts and rasters to an equal-area CRS before area fractions.",
        "3. Use fractional pixel coverage at district boundaries; never centroid-in-polygon assignment for coarse cells.",
        "4. Report valid-pixel coverage for every district and reject a variable if any district has <95% expected coverage without a documented physical reason.",
        "5. Retain untransformed numerator, denominator, valid area, and final transformed feature.",
        "6. Compare extracted national/district aggregates with publisher summaries when available.",
        "7. Freeze the 64-row district feature table before fitting any choice model.",
        "",
        "## Model-entry contract",
        "",
        "The first comparison adds the four frozen constructs jointly to the strongest gravity baseline. "
        "A ridge penalty is tuned only inside training folds. No stepwise selection, outcome-guided feature "
        "dropping, destination fixed effects, or alternative transformations are allowed in the primary run. "
        "Pre-specified robustness substitutions are JRC surface water for flood exposure, VIIRS 2020 for "
        "settlement intensity, and GHS-POP 2020 for BBS population.",
        "",
        "## Verified source facts",
        "",
        "- [JRC Global Surface Water](https://global-surface-water.appspot.com/download) provides tiled downloads and yearly/monthly history; later 2022–2024 layers exist but require strict event cutoffs.",
        "- [GHSL](https://human-settlement.emergency.copernicus.eu/dataToolsOverview.php) provides open multitemporal built-up and population products through the 2020 observed epoch.",
        "- [ESA WorldCover](https://esa-worldcover.org/en/data-access) supplies 10 m 2020 and 2021 maps under CC BY 4.0 and warns that the versions use different algorithms.",
        "- [Travel time to cities and ports](https://figshare.com/articles/dataset/Travel_time_to_cities_and_ports_in_the_year_2015/7638134) is a 2015, 30-arc-second modelled accessibility surface.",
        "- [Global Flood Database](https://developers.google.com/earth-engine/datasets/catalog/GLOBAL_FLOOD_DB_MODIS_EVENTS_V1) maps 913 selected events from 2000–2018 and is not a complete census of flooding.",
        "- [CHIRPS v3](https://www.chc.ucsb.edu/data/chirps3) supplies 0.05-degree rainfall from 1981 to near-present.",
        "- [VIIRS annual nighttime lights](https://eogdata.mines.edu/products/vnl/) supplies approximately 500 m annual radiance composites.",
        "",
        "The complete registry, including licensing and limitations, is in `bemp_stage3_gis_source_registry.csv`.",
        "",
    ]
    (REPORTS / "bemp_stage3_gis_feature_spec.md").write_text("\n".join(lines), encoding="utf-8")
    print(registry[["priority", "feature_family", "dataset", "model_role", "download_status"]].to_string(index=False))


if __name__ == "__main__":
    main()
